export interface Project {
  id: number
  slug: string
  title: string
  location: string
  year: string
  category: string
  description: string
  image: string
  gallery: string[]
  videoUrl?: string
  stats: {
    area: string
    duration: string
  }
  featured: boolean
  status: "Completed" | "In Progress" | "Planned"
}

export const allProjects: Project[] = [
  {
    id: 1,
    slug: "ambala-airforce-station",
    title: "Ambala Airforce Station",
    location: "Ambala, Haryana",
    year: "2023",
    category: "Government & Defense",
    description: "A prestigious defense project featuring advanced facade systems and high-security entrance solutions for the Indian Air Force station. The project encompasses comprehensive glazing systems designed to meet stringent defense standards while maintaining aesthetic appeal. Our team implemented specialized blast-resistant glass panels, automated access control systems, and weather-resistant aluminum cladding that ensures durability in extreme conditions. The installation includes over 15,000 square feet of high-performance curtain walls with thermal break technology, ensuring energy efficiency while meeting the rigorous security requirements of a military installation.",
    image: "/projects/Jubilee Juncttion/WhatsApp Image 2024-06-24 at 14.05.36_ed990af8.jpg",
    gallery: [
      "/projects/Jubilee Juncttion/WhatsApp Image 2024-06-24 at 14.05.36_ed990af8.jpg",
    ],
    stats: {
      area: "15,000 sq ft",
      duration: "8 months",
    },
    featured: true,
    status: "Completed",
  },
  {
    id: 2,
    slug: "iit-jammu",
    title: "IIT Jammu",
    location: "Jammu, Jammu & Kashmir",
    year: "2024",
    category: "Education",
    description: "Modern educational infrastructure for one of India's premier technological institutes, featuring state-of-the-art curtain wall systems and energy-efficient glazing solutions. This landmark project for IIT Jammu includes advanced architectural glazing across multiple academic buildings, incorporating sustainable design principles and cutting-edge facade technology. The installation features over 25,000 square feet of low-E glass panels with superior thermal insulation properties, complemented by anodized aluminum framing systems in contemporary finishes. Our team delivered innovative sun control solutions and automated ventilation systems that create an optimal learning environment while significantly reducing energy consumption.",
    image: "/projects/IIT Jammu/IMG-20240509-WA0001.jpg",
    gallery: [
      "/projects/IIT Jammu/IMG-20240509-WA0001.jpg",
      "/projects/IIT Jammu/IMG-20240509-WA0002.jpg",
      "/projects/IIT Jammu/IMG-20240509-WA0003.jpg",
    ],
    stats: {
      area: "25,000 sq ft",
      duration: "12 months",
    },
    featured: true,
    status: "Completed",
  },
  {
    id: 3,
    slug: "tynor",
    title: "Tynor Corporate Headquarters",
    location: "Delhi NCR",
    year: "2023",
    category: "Corporate",
    description: "A striking corporate headquarters showcasing premium glass and aluminum facade systems that reflect Tynor's commitment to innovation and excellence in healthcare products. This comprehensive project features over 40,000 square feet of architectural glazing with a sophisticated mix of clear, tinted, and reflective glass panels creating a dynamic visual identity. The exterior envelope includes unitized curtain wall systems with concealed drainage, ensuring weather-tight performance and minimal maintenance. Interior applications feature elegant glass partitions, sliding doors, and railings that promote open collaboration while maintaining acoustic privacy. The project also incorporates advanced BMS-integrated shading systems and high-performance automatic doors at all entry points.",
    image: "/projects/Tynor/0d404ec1-fd0c-4717-bde4-663e072be0ec.JPG",
    gallery: [
      "/projects/Tynor/0d404ec1-fd0c-4717-bde4-663e072be0ec.JPG",
      "/projects/Tynor/322418f0-e9d2-4b4a-be42-12a376e843b1.JPG",
      "/projects/Tynor/42ff655a-ccad-48d7-9b40-bff256ac641d.JPG",
      "/projects/Tynor/5507bd45-8b80-44ad-a108-3f5c0f384870.JPG",
      "/projects/Tynor/601feb9e-a039-4946-a4e6-f0d869df58d9.JPG",
      "/projects/Tynor/68637d1c-53eb-4496-9b0e-4c8983a42c75.JPG",
      "/projects/Tynor/8d5e0bca-e792-4470-9bad-41a4f051f97b.JPG",
      "/projects/Tynor/9a558d25-f3e7-4baf-8f68-a928c7432fb2.JPG",
      "/projects/Tynor/c6949dc9-8215-469f-9cf4-7106b9c538c5.JPG",
      "/projects/Tynor/c7f241e3-0004-4eb6-a8e0-8686f6dc9356.JPG",
    ],
    stats: {
      area: "40,000 sq ft",
      duration: "14 months",
    },
    featured: true,
    status: "Completed",
  },
  {
    id: 4,
    slug: "ashoka-dnova",
    title: "Ashoka Dnova",
    location: "Punjab",
    year: "2023",
    category: "Commercial",
    description: "An innovative commercial development featuring contemporary glass architecture and premium entrance systems. This mixed-use development showcases over 35,000 square feet of high-performance curtain wall systems with thermally broken aluminum profiles and energy-efficient double glazed units. The facade design incorporates vertical and horizontal emphasis lines creating a modern architectural statement while optimizing natural daylighting. The project includes sophisticated automatic sliding doors with motion sensors, access control integration, and anti-panic features. Interior spaces feature frameless glass partitions with acoustic ratings up to 42 dB, stainless steel and glass railings meeting international safety standards, and custom-designed canopies at main entrances.",
    image: "/projects/Ashoka Dnova/IMG-20240516-WA0019.jpg",
    gallery: [
      "/projects/Ashoka Dnova/IMG-20240516-WA0019.jpg",
      "/projects/Ashoka Dnova/IMG-20240516-WA0020.jpg",
      "/projects/Ashoka Dnova/IMG-20240516-WA0021.jpg",
      "/projects/Ashoka Dnova/IMG-20240516-WA0022.jpg",
      "/projects/Ashoka Dnova/IMG-20240516-WA0023.jpg",
      "/projects/Ashoka Dnova/IMG-20240516-WA0024.jpg",
      "/projects/Ashoka Dnova/IMG-20240516-WA0025.jpg",
      "/projects/Ashoka Dnova/IMG-20240516-WA0026.jpg",
      "/projects/Ashoka Dnova/IMG-20240516-WA0027.jpg",
      "/projects/Ashoka Dnova/IMG-20240516-WA0028.jpg",
    ],
    stats: {
      area: "35,000 sq ft",
      duration: "10 months",
    },
    featured: true,
    status: "Completed",
  },
  {
    id: 5,
    slug: "indore-office-haworth",
    title: "Haworth Office Indore",
    location: "Indore, Madhya Pradesh",
    year: "2024",
    category: "Corporate",
    description: "A cutting-edge office space for Haworth featuring premium glass partitions, modern entrance systems, and integrated interior glazing solutions that exemplify workplace innovation. This 30,000 square foot project demonstrates the latest trends in corporate architecture with extensive use of demountable glass partition systems allowing flexible space reconfiguration. The installation features full-height glazed walls with minimal aluminum framing, creating transparency while maintaining acoustic performance. Custom automatic door systems at the main entrance include advanced sensors and access control integration. The project incorporates specialty applications including glass whiteboards, decorative film applications, and privacy glass solutions. Sustainable design elements include daylight harvesting systems and high-performance glass with excellent U-values.",
    image: "/projects/indore office haworth/Picture1.jpg",
    gallery: [
      "/projects/indore office haworth/Picture1.jpg",
      "/projects/indore office haworth/Picture2.jpg",
      "/projects/indore office haworth/Picture3.jpg",
      "/projects/indore office haworth/Picture4.jpg",
      "/projects/indore office haworth/Picture5.jpg",
      "/projects/indore office haworth/Picture6.jpg",
      "/projects/indore office haworth/Picture7.jpg",
      "/projects/indore office haworth/Picture8.jpg",
    ],

    stats: {
      area: "30,000 sq ft",
      duration: "9 months",
    },
    featured: true,
    status: "Completed",
  },
  {
    id: 6,
    slug: "rishihood-university",
    title: "Rishihood University",
    location: "Sonipat, Haryana",
    year: "2023",
    category: "Education",
    description: "A modern educational campus featuring expansive glass facades, skylights, and innovative architectural glazing that creates inspiring learning environments. This transformative project spans over 50,000 square feet across multiple academic and administrative buildings. The curtain wall systems incorporate solar control glass reducing heat gain by 60% while maximizing natural light penetration. Structural glazing applications include dramatic double-height entrance atriums with point-fixed glass assemblies creating column-free spaces. The project features automated sliding doors at all major access points, hurricane-resistant glass in exposed locations, and custom aluminum cladding in university brand colors. Sustainable features include photovoltaic-integrated glazing and rainwater harvesting systems.",
    image: "/projects/Rishihood University/Narsi/IMG-20230215-WA0001.jpg",
    gallery: [
      "/projects/Rishihood University/Narsi/IMG-20230215-WA0001.jpg",
      "/projects/Rishihood University/Narsi/IMG-20230215-WA0002.jpg",
      "/projects/Rishihood University/Narsi/IMG-20230215-WA0003.jpg",
      "/projects/Rishihood University/Narsi/IMG-20230215-WA0004.jpg",
      "/projects/Rishihood University/Narsi/IMG-20230215-WA0005.jpg",
      "/projects/Rishihood University/Narsi/IMG-20230215-WA0006.jpg",
      "/projects/Rishihood University/Narsi/IMG-20230215-WA0007.jpg",
      "/projects/Rishihood University/Narsi/IMG-20230215-WA0008.jpg",
      "/projects/Rishihood University/Narsi/IMG-20230215-WA0009.jpg",
      "/projects/Rishihood University/Narsi/IMG-20230215-WA0010.jpg",
    ],
    stats: {
      area: "50,000 sq ft",
      duration: "16 months",
    },
    featured: true,
    status: "Completed",
  },
  {
    id: 7,
    slug: "elante-mall",
    title: "Elante Mall",
    location: "Chandigarh",
    year: "2022",
    category: "Retail",
    description: "One of North India's largest shopping destinations featuring massive glass storefronts, automatic entrance systems, and premium retail glazing across multiple levels. The project encompasses over 100,000 square feet of architectural glass and aluminum systems. Storefront systems feature large-format glass panels up to 12 feet in height with minimal sightlines, creating attractive display windows for premium retailers. The installation includes hundreds of automatic door systems from leading manufacturers, integrated with building management systems for energy optimization. Interior applications feature glass balustrades at all levels meeting stringent safety codes, decorative glass features in common areas, and sophisticated wayfinding signage systems.",
    image: "/projects/elante/elante railing.jpg",
    gallery: [
      "/projects/elante/elante railing.jpg",
    ],
    stats: {
      area: "100,000 sq ft",
      duration: "20 months",
    },
    featured: false,
    status: "Completed",
  },
  {
    id: 8,
    slug: "vadodara-airport",
    title: "Vadodara Airport",
    location: "Vadodara, Gujarat",
    year: "2024",
    category: "Infrastructure",
    description: "A major airport infrastructure project featuring high-performance curtain walls, blast-resistant glazing, and sophisticated automated door systems meeting international aviation standards. This critical infrastructure project covers 60,000 square feet of specialized facade systems designed for extreme durability and security. The curtain wall assembly incorporates laminated safety glass with interlayer films providing blast mitigation properties while maintaining optical clarity. High-speed automatic sliding doors at passenger entry points feature fail-safe mechanisms and integration with access control systems. The project includes specialty applications such as bird-strike resistant glass at critical locations, acoustic glazing for noise reduction, and climate-adaptive systems handling high temperature variations.",
    image: "/projects/Vadodra Airport/IMG-20240508-WA0001.jpg",
    gallery: [
      "/projects/Vadodra Airport/IMG-20240508-WA0001.jpg",
      "/projects/Vadodra Airport/IMG-20240508-WA0002.jpg",
      "/projects/Vadodra Airport/IMG-20240508-WA0003.jpg",
      "/projects/Vadodra Airport/IMG-20240508-WA0004.jpg",
      "/projects/Vadodra Airport/IMG-20240508-WA0005.jpg",
      "/projects/Vadodra Airport/IMG-20240508-WA0006.jpg",
      "/projects/Vadodra Airport/IMG-20240508-WA0007.jpg",
      "/projects/Vadodra Airport/IMG-20240508-WA0008.jpg",
      "/projects/Vadodra Airport/IMG-20240508-WA0009.jpg",
      "/projects/Vadodra Airport/IMG-20240508-WA0010.jpg",
    ],
    stats: {
      area: "60,000 sq ft",
      duration: "18 months",
    },
    featured: false,
    status: "Completed",
  },
  {
    id: 9,
    slug: "dmrc",
    title: "Delhi Metro Rail Corporation",
    location: "Delhi NCR",
    year: "2023",
    category: "Infrastructure",
    description: "Critical metro infrastructure project featuring specialized glazing systems, security entrance solutions, and weather-resistant facades designed for high-traffic public transportation facilities. The project spans multiple metro stations covering 80,000 square feet of architectural glass and aluminum systems. Curtain walls incorporate laminated safety glass with UV protection and anti-graffiti coatings suitable for public spaces. Automated fare gate enclosures feature toughened glass with access control integration. The installation includes noise barriers with acoustic glazing reducing sound transmission by 35 dB, stainless steel cladding in high-wear areas, and modular partition systems for commercial spaces within stations.",
    image: "/projects/DMRC/275863954_3246308608921841_7273523327283602996_n.jpg",
    gallery: [
      "/projects/DMRC/275863954_3246308608921841_7273523327283602996_n.jpg",
      "/projects/DMRC/277748744_3246308568921845_3305892295589580749_n.jpg",
      "/projects/DMRC/277778379_3246308578921844_383075612462568194_n.jpg",
      "/projects/DMRC/277814832_3246308665588502_3155508649349152473_n.jpg",
      "/projects/DMRC/277815818_3246308702255165_8208967910276463378_n.jpg",
      "/projects/DMRC/277983430_3246308655588503_7644330291025016300_n.jpg",
    ],
    stats: {
      area: "80,000 sq ft",
      duration: "22 months",
    },
    featured: false,
    status: "Completed",
  },
  {
    id: 10,
    slug: "nabard",
    title: "NABARD Regional Office",
    location: "North India",
    year: "2023",
    category: "Government",
    description: "A sustainable government office building featuring energy-efficient glazing systems, modern entrance solutions, and environmentally responsible facade design for the National Bank for Agriculture and Rural Development. This GRIHA-certified project incorporates 28,000 square feet of high-performance glazing systems optimized for energy conservation. The facade features double-skin curtain wall technology with integrated shading devices reducing cooling loads by 40%. Low-E glass with argon fill provides superior thermal insulation with U-values of 1.2 W/m²K. Automatic doors at entrances feature energy-saving modes and air curtain integration. The project includes daylight-responsive dimming systems, rooftop skylight installations, and rainwater harvesting infrastructure.",
    image: "/projects/NABARD PICS/IMG_20180721_155856.jpg",
    gallery: [
      "/projects/NABARD PICS/IMG_20180721_155856.jpg",
      "/projects/NABARD PICS/IMG_20180721_155914.jpg",
      "/projects/NABARD PICS/IMG_20180721_155933.jpg",
      "/projects/NABARD PICS/IMG_20180721_160010.jpg",
      "/projects/NABARD PICS/IMG_20180721_160103.jpg",
      "/projects/NABARD PICS/IMG_20180721_161139.jpg",
      "/projects/NABARD PICS/IMG_20180721_161155.jpg",
      "/projects/NABARD PICS/IMG_20180721_161318.jpg",
      "/projects/NABARD PICS/IMG_20180721_161331.jpg",
      "/projects/NABARD PICS/IMG_20180721_161339.jpg",
    ],
    videoUrl: "/projects/NABARD PICS/VID_20180721_162208.mp4",

    stats: {
      area: "28,000 sq ft",
      duration: "11 months",
    },
    featured: false,
    status: "Completed",
  },
  {
    id: 11,
    slug: "iit-roorkee-vmzinc",
    title: "IIT Roorkee - VMZinc Installation",
    location: "Roorkee, Uttarakhand",
    year: "2023",
    category: "Education",
    description: "Prestigious educational project featuring premium VMZinc cladding systems, architectural glazing, and modern facade solutions for India's historic engineering institution. This landmark renovation project combines traditional architecture with contemporary materials across 22,000 square feet. The installation features standing seam zinc cladding in natural ANTHRA finish, providing a distinctive aesthetic while ensuring 100+ year durability. Complementary curtain wall systems incorporate high-performance glass with low-E coatings optimized for the northern climate. The project includes custom aluminum window systems matching historic profiles, automated entrance doors with heritage-appropriate finishes, and zinc gutters and downspouts integrated with the existing drainage infrastructure.",
    image: "/projects/IIT Roorkee-vmzinc/PHOTO-2022-03-08-14-05-43.jpg",
    gallery: [
      "/projects/IIT Roorkee-vmzinc/PHOTO-2022-03-08-14-05-43.jpg",
      "/projects/IIT Roorkee-vmzinc/PHOTO-2022-03-08-14-05-44 (1).jpg",
      "/projects/IIT Roorkee-vmzinc/PHOTO-2022-03-08-14-05-44 (2).jpg",
      "/projects/IIT Roorkee-vmzinc/PHOTO-2022-03-08-14-05-44.jpg",
      "/projects/IIT Roorkee-vmzinc/PHOTO-2022-03-08-14-05-45 (3).jpg",
      "/projects/IIT Roorkee-vmzinc/PHOTO-2022-03-08-14-05-45.jpg",
      "/projects/IIT Roorkee-vmzinc/PHOTO-2022-03-08-14-05-46 (4).jpg",
      "/projects/IIT Roorkee-vmzinc/PHOTO-2022-03-08-14-05-46 (5).jpg",
      "/projects/IIT Roorkee-vmzinc/PHOTO-2022-03-08-14-05-46.jpg",
      "/projects/IIT Roorkee-vmzinc/PHOTO-2022-03-08-14-05-47 (6).jpg",
    ],
    stats: {
      area: "22,000 sq ft",
      duration: "10 months",
    },
    featured: false,
    status: "Completed",
  },
  {
    id: 12,
    slug: "power-grid-kurukshetra",
    title: "Power Grid Corporation - Kurukshetra",
    location: "Kurukshetra, Haryana",
    year: "2024",
    category: "Government",
    description: "Critical power infrastructure facility featuring secure entrance systems, blast-resistant glazing, and durable facade solutions meeting stringent utility industry standards. This high-security project encompasses 18,000 square feet of specialized glazing and cladding systems. The installation features laminated glass with interlayers providing blast mitigation and forced-entry resistance meeting ASTM F1642 standards. Automatic sliding doors include electromagnetic locking systems, access control integration, and emergency egress functionality. Curtain walls incorporate thermally broken aluminum profiles with seismic design considerations. The project includes specialized applications such as control room glazing with EMI shielding, fire-rated glass assemblies, and weatherproof aluminum louvers for mechanical equipment screening.",
    image: "/projects/POWER GRID-KURUKSHETRA/1641103667786.jpg",
    gallery: [
      "/projects/POWER GRID-KURUKSHETRA/1641103667786.jpg",
      "/projects/POWER GRID-KURUKSHETRA/178fc7e5-ee36-47fc-b982-ce88c3e5e8f9.JPG",
      "/projects/POWER GRID-KURUKSHETRA/344a2c94-9621-4a0d-a89e-8e5885ddb84c.JPG",
      "/projects/POWER GRID-KURUKSHETRA/3e5385d0-dbcb-4265-85a3-ff23640df295.JPG",
      "/projects/POWER GRID-KURUKSHETRA/42e4b6fd-e97f-4856-936a-f74a0a1692b8.JPG",
      "/projects/POWER GRID-KURUKSHETRA/44c27edc-c6a4-4c02-8633-1dfcec961ed4.JPG",
      "/projects/POWER GRID-KURUKSHETRA/79813b1e-5c1a-4906-923c-fba916f1bcd2.JPG",
      "/projects/POWER GRID-KURUKSHETRA/828c3184-8ead-42c5-a464-c044fe60bfcd.JPG",
      "/projects/POWER GRID-KURUKSHETRA/9971283a-23bc-4335-b2bc-366ed8474228.JPG",
      "/projects/POWER GRID-KURUKSHETRA/e9734246-8467-4a0b-b726-99dbcad15975.JPG",
    ],
    stats: {
      area: "18,000 sq ft",
      duration: "9 months",
    },
    featured: false,
    status: "Completed",
  },
  {
    id: 13,
    slug: "teleperformance",
    title: "Teleperformance Corporate Office",
    location: "Gurgaon, Haryana",
    year: "2023",
    category: "Corporate",
    description: "A world-class BPO facility featuring extensive glass partitioning, acoustic glazing systems, and modern entrance solutions designed for large-scale operations. This 45,000 square foot project optimizes workspace efficiency with flexible demountable partition systems. The installation features single and double glazed partitions with acoustic performance up to 45 dB, essential for call center operations. Full-height glass walls create transparent meeting rooms while maintaining speech privacy. Automatic door systems at main entrances and internal circulation zones include touchless activation and access control integration. The project incorporates branded glass manifestations for way-finding and safety, custom reception desks with integrated glazing, and energy-efficient HVAC zoning enabled by the partition layout.",
    image: "/projects/Teleperformance/PHOTO-2018-07-12-21-46-20.jpg",
    gallery: [
      "/projects/Teleperformance/PHOTO-2018-07-12-21-46-20.jpg",
      "/projects/Teleperformance/PHOTO-2018-07-12-21-46-21.jpg",
      "/projects/Teleperformance/PHOTO-2018-07-12-21-46-23.jpg",
      "/projects/Teleperformance/PHOTO-2018-07-12-21-46-24.jpg",
      "/projects/Teleperformance/PHOTO-2018-07-12-21-46-25.jpg",
      "/projects/Teleperformance/PHOTO-2018-07-12-21-46-26.jpg",
      "/projects/Teleperformance/PHOTO-2018-07-12-21-46-29.jpg",
      "/projects/Teleperformance/PHOTO-2018-07-12-21-46-30.jpg",
      "/projects/Teleperformance/PHOTO-2018-07-12-21-46-31.jpg",
      "/projects/Teleperformance/PHOTO-2018-07-12-21-46-33.jpg",
    ],
    stats: {
      area: "45,000 sq ft",
      duration: "12 months",
    },
    featured: false,
    status: "Completed",
  },
  {
    id: 14,
    slug: "ashoka-university",
    title: "Ashoka University",
    location: "Sonipat, Haryana",
    year: "2022",
    category: "Education",
    description: "A prestigious liberal arts university campus featuring contemporary glazing systems, sustainable facade solutions, and innovative architectural glass applications. This comprehensive campus project covers 65,000 square feet across academic buildings, libraries, and student centers. The curtain wall systems feature high-performance glass with selective coatings optimizing daylighting while reducing solar heat gain by 55%. Structural glazing applications create column-free spaces in lecture halls and common areas. The installation includes operable windows with natural ventilation capabilities, automated entrance systems at all major buildings, and custom skylight assemblies illuminating interior corridors. Sustainable design features include electrochromic glazing in south-facing applications and integrated photovoltaic panels.",
    image: "/projects/Ashoka/1517906556.CENTRAL LIBARY.JPG",
    gallery: [
      "/projects/Ashoka/1517906556.CENTRAL LIBARY.JPG",
      "/projects/Ashoka/1517918556.DORMA ELANTE MALL CHANDIGARH.jpg",
      "/projects/Ashoka/1517919693.AIRPORT AMRITSAR (1).jpg",
      "/projects/Ashoka/1517919843.DORMA DHARAMSHALA STADIUM-1.jpg",
      "/projects/Ashoka/1517986472.GVK Glass Handrail (1).JPG",
      "/projects/Ashoka/1517986472.GVK Glass Handrail (2).jpg",
      "/projects/Ashoka/1517988268.DORMA ALEXA PARTITION ASHOKA UNIVERSITY SONIPAT.jpg",
      "/projects/Ashoka/1517988268.DORMA ALEXA WITH DOOR -ASHOKA UNIVERSITY SONIPAT.jpg",
      "/projects/Ashoka/1517988268.HUNTER DOUGLUS WITH HAVELLS LIGHT.jpg",
      "/projects/Ashoka/1517990819.IMG-20170918-WA0037.jpg",
    ],
    stats: {
      area: "65,000 sq ft",
      duration: "18 months",
    },
    featured: false,
    status: "Completed",
  },
  {
    id: 15,
    slug: "jubilee-junction",
    title: "Jubilee Junction",
    location: "Chandigarh",
    year: "2023",
    category: "Retail",
    description: "A vibrant retail and entertainment complex featuring expansive glass storefronts, modern entrance systems, and eye-catching facade design. This 55,000 square foot mixed-use development showcases contemporary retail architecture with floor-to-ceiling glazing creating attractive display windows. The installation features butt-glazed storefronts with structural silicone joints eliminating vertical mullions for unobstructed views. High-traffic automatic sliding doors include heavy-duty operators rated for 1 million+ cycles and integration with footfall counting systems. Interior applications feature glass balustrades at circulation areas, decorative laminated glass with custom interlayers, and digital signage integration. The project includes sophisticated exterior lighting design highlighting the glass and aluminum facades.",
    image: "/projects/Jubilee Juncttion/WhatsApp Image 2024-06-24 at 14.05.36_ed990af8.jpg",
    gallery: [
      "/projects/Jubilee Juncttion/WhatsApp Image 2024-06-24 at 14.05.36_ed990af8.jpg",
    ],
    stats: {
      area: "55,000 sq ft",
      duration: "14 months",
    },
    featured: false,
    status: "Completed",
  },
  {
    id: 16,
    slug: "jubilee-walk-alexa",
    title: "Jubilee Walk Alexa",
    location: "Chandigarh",
    year: "2024",
    category: "Retail",
    description: "An upscale retail destination featuring premium glass facades, sophisticated entrance systems, and contemporary architectural glazing. This 38,000 square foot project establishes a new standard for retail design in the region. The storefront systems feature extra-clear low-iron glass providing true color rendition for merchandise display. Automatic entrance systems include revolving doors at main entries with energy-efficient vestibules and high-speed sliding doors at secondary entrances. The curtain wall incorporates fritted glass patterns reducing bird strikes while adding architectural interest. Interior applications include glass elevator enclosures, frameless glass railings at escalators, and custom glass canopies at entry plazas. The project features smart building integration with automated shading and climate control.",
    image: "/projects/Jubilee Walk Alexa/IMG-20240309-WA0021.jpg",
    gallery: [
      "/projects/Jubilee Walk Alexa/IMG-20240309-WA0021.jpg",
      "/projects/Jubilee Walk Alexa/IMG-20240309-WA0022.jpg",
      "/projects/Jubilee Walk Alexa/IMG-20240309-WA0023.jpg",
      "/projects/Jubilee Walk Alexa/IMG-20240309-WA0024.jpg",
      "/projects/Jubilee Walk Alexa/IMG-20240309-WA0025.jpg",
      "/projects/Jubilee Walk Alexa/IMG-20240309-WA0026.jpg",
      "/projects/Jubilee Walk Alexa/IMG-20240309-WA0027.jpg",
      "/projects/Jubilee Walk Alexa/IMG-20240309-WA0028.jpg",
      "/projects/Jubilee Walk Alexa/IMG-20240309-WA0029.jpg",
      "/projects/Jubilee Walk Alexa/IMG-20240309-WA0030.jpg",
    ],
    stats: {
      area: "38,000 sq ft",
      duration: "11 months",
    },
    featured: false,
    status: "Completed",
  },
  {
    id: 17,
    slug: "coca-cola-ludhiana",
    title: "Coca-Cola Bottling Plant",
    location: "Ludhiana, Punjab",
    year: "2023",
    category: "Industrial",
    description: "An industrial facility featuring durable glazing systems, industrial entrance solutions, and weather-resistant facades designed for manufacturing operations. This 32,000 square foot project combines functionality with corporate branding standards. The installation features impact-resistant glazing in production areas meeting industrial safety requirements, aluminum composite panel cladding in Coca-Cola corporate colors, and industrial-grade automatic doors with dust and moisture sealing. Office areas incorporate standard commercial curtain wall systems with acoustic performance. The project includes specialized applications such as cleanroom glazing for quality control laboratories, fire-rated assemblies at production boundaries, and explosion-relief panels in designated areas.",
    image: "/projects/Coca cola,ldh/WhatsApp Image 2021-02-22 at 3.58.09 PM.JPEG",
    gallery: [
      "/projects/Coca cola,ldh/WhatsApp Image 2021-02-22 at 3.58.09 PM.JPEG",
    ],
    stats: {
      area: "32,000 sq ft",
      duration: "10 months",
    },
    featured: false,
    status: "Completed",
  },
  {
    id: 18,
    slug: "hpcl-bhatinda",
    title: "HPCL Refinery - Bhatinda",
    location: "Bhatinda, Punjab",
    year: "2022",
    category: "Industrial",
    description: "A major petroleum refinery facility featuring specialized industrial glazing, secure entrance systems, and explosion-resistant facades meeting stringent oil & gas industry standards. This critical infrastructure project covers 25,000 square feet of specialized systems designed for hazardous environments. The installation features laminated glass assemblies with blast mitigation properties, aluminum framing systems with enhanced corrosion resistance for petrochemical environments, and automatic doors with explosion-proof actuators rated for Zone 2 hazardous areas. Control room glazing provides blast protection while maintaining visibility of operations. The project includes acid-resistant coatings, UV-resistant sealants, and comprehensive pressure relief mechanisms.",
    image: "/projects/HPCL Bhatinda/IMG-20190213-WA0005.jpg",
    gallery: [
      "/projects/HPCL Bhatinda/IMG-20190213-WA0005.jpg",
      "/projects/HPCL Bhatinda/IMG-20190213-WA0006.jpg",
      "/projects/HPCL Bhatinda/IMG-20190213-WA0007.jpg",
      "/projects/HPCL Bhatinda/IMG-20190213-WA0008.jpg",
    ],
    stats: {
      area: "25,000 sq ft",
      duration: "13 months",
    },
    featured: false,
    status: "Completed",
  },
  {
    id: 19,
    slug: "microtek",
    title: "Microtek Corporate Office",
    location: "Delhi NCR",
    year: "2023",
    category: "Corporate",
    description: "A technology company headquarters featuring modern glass architecture, intelligent entrance systems, and energy-efficient facade solutions. This 28,000 square foot project showcases contemporary corporate design with extensive use of architectural glass. The curtain wall system incorporates high-performance glazing with excellent thermal and solar control properties reducing energy consumption by 35%. Automated entrance systems include touchless sensors and integration with visitor management systems. Interior applications feature demountable glass partitions allowing workspace reconfiguration, glass whiteboards in meeting rooms, and custom reception areas with backlit glass features. The project includes smart building technologies with automated blinds, occupancy sensors, and climate control optimization.",
    image: "/projects/Microtek/03da1e6d-48a1-40c5-82be-df4d925e4035.JPG",
    gallery: [
      "/projects/Microtek/03da1e6d-48a1-40c5-82be-df4d925e4035.JPG",
      "/projects/Microtek/0cedca88-58a8-4211-87c2-c5b82127b95c.JPG",
      "/projects/Microtek/28b11883-3265-4a3a-a6ec-a7f6ca1bdcf8.JPG",
      "/projects/Microtek/3436298c-c292-4885-b22b-f67cf3f19532.JPG",
      "/projects/Microtek/3e317e65-0618-4905-a459-c17c862877b3.JPG",
      "/projects/Microtek/42ad959b-5602-49e6-accf-11b97f0dd812.JPG",
      "/projects/Microtek/556ab2a4-6212-4f70-acae-9288ff8a0224.JPG",
      "/projects/Microtek/8d1151d1-61c7-478f-a52a-63b8dca94787.JPG",
      "/projects/Microtek/b64afd69-c144-4098-82ad-ba5999d4521d.JPG",
      "/projects/Microtek/bcbcf114-2b13-4e79-98e7-0803a4e3c221.JPG",
    ],
    stats: {
      area: "28,000 sq ft",
      duration: "9 months",
    },
    featured: false,
    status: "Completed",
  },
  {
    id: 20,
    slug: "pbti",
    title: "Punjab Biotechnology Incubator",
    location: "Mohali, Punjab",
    year: "2024",
    category: "Research & Development",
    description: "A state-of-the-art biotechnology research facility featuring specialized cleanroom glazing, controlled entrance systems, and contamination-resistant facades. This 20,000 square foot facility incorporates specialized systems for life sciences research. The installation features hermetically sealed glazing systems for cleanroom environments with smooth, easy-to-clean surfaces. Automatic doors include airlocks and pressure differential maintenance for contamination control. Laboratory-grade aluminum framing systems resist chemical exposure. The project includes viewing windows for process monitoring, pass-through chambers with double-door interlocks, and specialized HVAC integration. Fire-rated assemblies protect critical research areas while maintaining required visibility and access.",
    image: "/projects/PBTI/_DEV8230.jpg",
    gallery: [
      "/projects/PBTI/_DEV8230.jpg",
      "/projects/PBTI/_DEV8243.jpg",
      "/projects/PBTI/2023-06-28.jpg",
      "/projects/PBTI/IMG_2867.jpg",
      "/projects/PBTI/Inauguration_PBTI_CM_Building.jpg",
    ],
    stats: {
      area: "20,000 sq ft",
      duration: "12 months",
    },
    featured: false,
    status: "Completed",
  },
  {
    id: 21,
    slug: "labour-bureau",
    title: "Labour Bureau Government Office",
    location: "Chandigarh",
    year: "2023",
    category: "Government",
    description: "A government administrative building featuring durable glazing systems, secure entrance solutions, and maintenance-friendly facades. This 24,000 square foot project provides functional, long-lasting building envelope solutions for a public sector facility. The curtain wall system features thermally broken aluminum profiles with polyester powder coating ensuring long-term durability and minimal maintenance. Automated entrance doors include access control integration and disabled-accessible features meeting ADAAG standards. The installation incorporates energy-efficient double glazed units with warm-edge spacers, anodized aluminum sun shades reducing cooling loads, and acoustic glazing for offices facing busy streets. The project meets government green building norms with GRIHA compliance documentation.",
    image: "/projects/Labour Bureau/09b4d9bf-2d53-4566-9a06-2bc3ab2a49b0.JPG",
    gallery: [
      "/projects/Labour Bureau/09b4d9bf-2d53-4566-9a06-2bc3ab2a49b0.JPG",
      "/projects/Labour Bureau/191957f8-d574-4d6f-9762-03d38d62402a.JPG",
      "/projects/Labour Bureau/2c8da044-2323-461c-ad52-420549043bc1.JPG",
      "/projects/Labour Bureau/46102f48-36f5-4eab-9a32-b58ddad81e32.JPG",
      "/projects/Labour Bureau/5ce67ddf-5464-4468-ba65-95a9d5cc5f1c.JPG",
      "/projects/Labour Bureau/901eaa2e-1cc4-455f-b1d9-721f381b8994.JPG",
      "/projects/Labour Bureau/9b08876c-8487-4dab-82b7-a8b3d66b6f8a.JPG",
      "/projects/Labour Bureau/9d33f7bd-3b9f-46b4-928e-a76f6c7b9002.JPG",
    ],
    stats: {
      area: "24,000 sq ft",
      duration: "11 months",
    },
    featured: false,
    status: "Completed",
  },
  {
    id: 22,
    slug: "haworth-office-punjab",
    title: "Haworth Regional Office",
    location: "Punjab",
    year: "2023",
    category: "Corporate",
    description: "A regional office showcasing Haworth's expertise in workspace solutions with integrated glass partitioning and modern entrance systems. This 18,000 square foot project demonstrates best practices in contemporary office design. The installation features Haworth's proprietary glass partition systems with acoustic performance tailored to various workspace zones. Full-height glazed walls create transparent meeting spaces while maintaining privacy with frosted interlayers. Automated sliding doors at entrances include proximity sensors and access control. The project showcases specialty applications including curved glass partitions in reception areas, glass marker boards, and integrated technology panels. Sustainable features include daylight harvesting and automated blinds reducing energy consumption.",
    image: "/projects/Haworth office/PHOTO-2019-12-23-16-35-15.jpg",
    gallery: [
      "/projects/Haworth office/PHOTO-2019-12-23-16-35-15.jpg",
      "/projects/Haworth office/PHOTO-2019-12-23-16-35-16.jpg",
      "/projects/Haworth office/PHOTO-2019-12-23-16-35-17 (1).jpg",
      "/projects/Haworth office/PHOTO-2019-12-23-16-35-17.jpg",
      "/projects/Haworth office/PHOTO-2019-12-23-16-35-18 (2).jpg",
      "/projects/Haworth office/PHOTO-2019-12-23-16-35-18 (3).jpg",
      "/projects/Haworth office/PHOTO-2019-12-23-16-35-18.jpg",
      "/projects/Haworth office/PHOTO-2019-12-23-16-35-19 (4).jpg",
      "/projects/Haworth office/PHOTO-2019-12-23-16-35-19.jpg",
      "/projects/Haworth office/PHOTO-2019-12-23-16-35-20 (5).jpg",
    ],
    stats: {
      area: "18,000 sq ft",
      duration: "7 months",
    },
    featured: false,
    status: "Completed",
  },
  {
    id: 23,
    slug: "tagore-theatre",
    title: "Tagore Theatre Renovation",
    location: "Chandigarh",
    year: "2022",
    category: "Cultural",
    description: "A historic cultural venue renovation featuring specialized acoustic glazing, modern entrance systems, and heritage-sensitive facade solutions. This 15,000 square foot renovation project balances preservation with modernization. The installation features acoustic glazing systems with STC ratings up to 52, critical for the performance venue. Automated entrance doors include panic hardware and crowd control features for public assembly occupancy. The curtain wall incorporates blast-resistant laminated glass meeting security requirements for public venues. Interior applications include sound-isolation vestibules, green room glazing with privacy controls, and specialized projection room windows. The project respects the building's heritage while providing contemporary performance and safety standards.",
    image: "/projects/tagore theatre/tagore theatre 2.jpg",
    gallery: [
      "/projects/tagore theatre/tagore theatre 2.jpg",
      "/projects/tagore theatre/tagore theatre 3.jpg",
      "/projects/tagore theatre/tagore theatre 5.jpg",
      "/projects/tagore theatre/tagore theatre.jpeg",
    ],
    stats: {
      area: "15,000 sq ft",
      duration: "10 months",
    },
    featured: false,
    status: "Completed",
  },
  {
    id: 24,
    slug: "noida-zinc-chhabra",
    title: "Chhabra Residence - Noida Zinc Installation",
    location: "Noida, Uttar Pradesh",
    year: "2024",
    category: "Residential",
    description: "A luxury residential project featuring premium zinc cladding, architectural glazing, and sophisticated entrance systems. This 8,000 square foot high-end residence showcases exceptional craftsmanship with standing seam zinc cladding in VMZINC ANTHRA finish providing a distinctive charcoal-grey aesthetic. Complementary curtain wall systems incorporate triple-glazed units with argon fill for superior thermal and acoustic insulation. Automated entrance systems include biometric access control and smart home integration. The project features floor-to-ceiling glass walls maximizing views, frameless glass balustrades at terraces, and custom aluminum windows with concealed drainage. Sustainable features include rainwater harvesting and solar-ready infrastructure.",
    image: "/projects/Noida-zinc-chhabra/515A1836.jpg",
    gallery: [
      "/projects/Noida-zinc-chhabra/515A1836.jpg",
      "/projects/Noida-zinc-chhabra/515A1851.jpg",
      "/projects/Noida-zinc-chhabra/515A1857.jpg",
      "/projects/Noida-zinc-chhabra/515A1865.jpg",
      "/projects/Noida-zinc-chhabra/515A1913.jpg",
      "/projects/Noida-zinc-chhabra/515A1927.jpg",
      "/projects/Noida-zinc-chhabra/IMG_3325.JPG",
      "/projects/Noida-zinc-chhabra/IMG_3326.JPG",
      "/projects/Noida-zinc-chhabra/IMG_3327.JPG",
      "/projects/Noida-zinc-chhabra/IMG-20200724-WA0012.jpg",
    ],
    stats: {
      area: "8,000 sq ft",
      duration: "8 months",
    },
    featured: false,
    status: "Completed",
  },
  {
    id: 25,
    slug: "karnal-residence",
    title: "Karnal Private Residence",
    location: "Karnal, Haryana",
    year: "2023",
    category: "Residential",
    description: "An elegant residential project featuring contemporary glazing solutions, automated entrance systems, and architectural aluminum work. This 6,500 square foot modern home incorporates floor-to-ceiling glazing creating seamless indoor-outdoor connections. The installation features high-performance double-glazed windows with low-E coatings and warm-edge spacers optimizing energy efficiency. Automated sliding doors at the main entrance and patio include smart home integration. Interior applications feature glass partitions creating open yet defined spaces, glass stair railings meeting safety codes, and custom shower enclosures. The project includes aluminum pergolas, louver systems for sun control, and powder-coated aluminum cladding accents.",
    image: "/projects/Karnal Residence/IMG-20231128-WA0008.jpg",
    gallery: [
      "/projects/Karnal Residence/IMG-20231128-WA0008.jpg",
      "/projects/Karnal Residence/IMG-20231128-WA0009.jpg",
      "/projects/Karnal Residence/IMG-20231128-WA0011.jpg",
      "/projects/Karnal Residence/IMG-20231128-WA0012.jpg",
      "/projects/Karnal Residence/IMG-20231128-WA0013.jpg",
      "/projects/Karnal Residence/IMG-20231128-WA0014.jpg",
      "/projects/Karnal Residence/IMG-20231128-WA0015.jpg",
      "/projects/Karnal Residence/IMG-20231128-WA0016.jpg",
      "/projects/Karnal Residence/IMG-20231227-WA0015.jpg",
      "/projects/Karnal Residence/IMG-20231227-WA0016.jpg",
    ],
    stats: {
      area: "6,500 sq ft",
      duration: "6 months",
    },
    featured: false,
    status: "Completed",
  },
  {
    id: 26,
    slug: "kurukshetra-residence",
    title: "Kurukshetra Villa",
    location: "Kurukshetra, Haryana",
    year: "2023",
    category: "Residential",
    description: "A luxury villa featuring premium glass and aluminum systems, modern entrance solutions, and sophisticated architectural detailing. This 7,200 square foot residence showcases contemporary residential architecture with extensive glazing. The installation features panoramic sliding door systems up to 20 feet wide creating expansive openings to outdoor spaces. High-performance windows incorporate multi-point locking systems and integrated blinds. Automated entrance systems include video intercom and access control. The project features custom glass canopies at entries, structural glass stairs with LED lighting, and frameless glass wine cellar enclosures. Exterior applications include aluminum composite panel cladding and decorative louver screens providing privacy while maintaining ventilation.",
    image: "/projects/Kurukshetra Residence/IMG_6028.jpg",
    gallery: [
      "/projects/Kurukshetra Residence/IMG_6028.jpg",
      "/projects/Kurukshetra Residence/IMG_6029.jpg",
      "/projects/Kurukshetra Residence/IMG_6030.jpg",
      "/projects/Kurukshetra Residence/IMG_6031.jpg",
      "/projects/Kurukshetra Residence/WhatsApp Image 2021-12-25 at 10.18.15 PM.jpeg",
      "/projects/Kurukshetra Residence/WhatsApp Image 2021-12-25 at 10.18.16 PM (1).jpeg",
      "/projects/Kurukshetra Residence/WhatsApp Image 2021-12-25 at 10.18.16 PM.jpeg",
      "/projects/Kurukshetra Residence/WhatsApp Image 2021-12-25 at 10.18.17 PM.jpeg",
    ],
    stats: {
      area: "7,200 sq ft",
      duration: "7 months",
    },
    featured: false,
    status: "Completed",
  },
  {
    id: 27,
    slug: "sidhu-farm-house",
    title: "Sidhu Farm House",
    location: "Punjab",
    year: "2024",
    category: "Residential",
    description: "A contemporary farm house featuring expansive glass facades, modern entrance systems, and integrated indoor-outdoor living spaces. This 9,000 square foot rural retreat combines modern architecture with natural surroundings. The installation features lift-and-slide door systems up to 24 feet wide creating unobstructed views of landscaped gardens. Floor-to-ceiling curtain walls incorporate high-performance glass with solar control coatings. Automated pocket doors provide seamless transitions between spaces. The project includes outdoor living areas with glass wind screens, infinity-edge pool with glass tile finishes, and custom aluminum pergola structures. Security features include impact-resistant glass and integrated alarm systems.",
    image: "/projects/Sidhu farm house/IMG_1953.JPG",
    gallery: [
      "/projects/Sidhu farm house/IMG_1953.JPG",
      "/projects/Sidhu farm house/IMG_1954.JPG",
      "/projects/Sidhu farm house/IMG_1955.JPG",
      "/projects/Sidhu farm house/IMG_1956 - Copy.JPG",
      "/projects/Sidhu farm house/IMG_1956.JPG",
      "/projects/Sidhu farm house/IMG_1957 - Copy.JPG",
      "/projects/Sidhu farm house/IMG_1957.JPG",
      "/projects/Sidhu farm house/PHOTO-2019-07-13-13-25-08.jpg",
      "/projects/Sidhu farm house/PHOTO-2019-07-13-13-25-09 (1) - Copy.jpg",
      "/projects/Sidhu farm house/PHOTO-2019-07-13-13-25-09 (1).jpg",
    ],
    stats: {
      area: "9,000 sq ft",
      duration: "10 months",
    },
    featured: false,
    status: "Completed",
  },
  {
    id: 28,
    slug: "ar-gurveer-kurali",
    title: "Architect Gurveer Residence",
    location: "Kurali, Punjab",
    year: "2023",
    category: "Residential",
    description: "An architect's own residence featuring innovative glazing solutions, contemporary entrance systems, and cutting-edge architectural detailing. This 5,800 square foot home serves as a showcase of residential design possibilities. The installation features experimental glass applications including electrochromic smart glass providing on-demand privacy and solar control. Structural glazing creates cantilevered glass boxes extending from the main structure. Pivot entrance doors feature oversized glass panels with minimal framing. Interior applications include backlit glass features, custom etched glass panels, and integrated mirror and glass systems. The project demonstrates sustainable design with passive solar orientation, natural ventilation strategies, and recycled glass aggregate in decorative concrete.",
    image: "/projects/Ar. Gurveer, Kurali/2f124078-74e4-4d51-a00f-458eeee54fda.JPG",
    gallery: [
      "/projects/Ar. Gurveer, Kurali/2f124078-74e4-4d51-a00f-458eeee54fda.JPG",
      "/projects/Ar. Gurveer, Kurali/49fa1602-9295-4528-9ced-722796d931f7.JPG",
      "/projects/Ar. Gurveer, Kurali/4b217539-20f6-4be1-bf05-9a6cee25ec35.JPG",
      "/projects/Ar. Gurveer, Kurali/6388906a-0c4a-4d84-a267-b2cf7120790b.JPG",
      "/projects/Ar. Gurveer, Kurali/69b72dcb-b130-4e75-986e-bfbd40664fea.JPG",
      "/projects/Ar. Gurveer, Kurali/802f04a1-799d-4a4a-a93c-c750a686e599.JPG",
      "/projects/Ar. Gurveer, Kurali/8bb1fe45-c1b2-4819-9a5f-c969ee025ad6.JPG",
      "/projects/Ar. Gurveer, Kurali/92da6fcd-ec2b-4d18-8026-8e8b6d6b720d.JPG",
      "/projects/Ar. Gurveer, Kurali/dc707a1e-7524-4199-8363-9209cbc77c06.JPG",
    ],
    stats: {
      area: "5,800 sq ft",
      duration: "9 months",
    },
    featured: false,
    status: "Completed",
  },
  {
    id: 29,
    slug: "beauty-palace",
    title: "Beauty Palace Salon",
    location: "Punjab",
    year: "2023",
    category: "Retail",
    description: "An upscale beauty salon featuring elegant glass facades, sophisticated entrance systems, and premium interior glazing. This 3,500 square foot high-end salon creates an atmosphere of luxury and sophistication. The storefront features extra-clear glass with minimal framing creating an inviting street presence. Automated entrance doors include soft-close mechanisms and climate control vestibules. Interior applications feature glass partitions creating semi-private treatment areas while maintaining visual openness, illuminated mirror walls with integrated lighting, and decorative laminated glass with custom patterns. The project includes specialty features such as backlit onyx glass at the reception desk, glass shelving displays for retail products, and sophisticated ambient lighting integration.",
    image: "/projects/Beauty Palace/c9ca0e6f-e9de-4b65-8cf7-0173cafc01c7.jpg",
    gallery: [
      "/projects/Beauty Palace/c9ca0e6f-e9de-4b65-8cf7-0173cafc01c7.jpg",
      "/projects/Beauty Palace/IMG-20190525-WA0002.jpg",
      "/projects/Beauty Palace/IMG-20190525-WA0003.jpg",
      "/projects/Beauty Palace/IMG-20190525-WA0005.jpg",
      "/projects/Beauty Palace/IMG-20190525-WA0006.jpg",
      "/projects/Beauty Palace/IMG-20190525-WA0007.jpg",
    ],
    stats: {
      area: "3,500 sq ft",
      duration: "4 months",
    },
    featured: false,
    status: "Completed",
  },
  {
    id: 30,
    slug: "hot-millions",
    title: "Hot Millions Restaurant",
    location: "Punjab",
    year: "2022",
    category: "Hospitality",
    description: "A vibrant restaurant featuring eye-catching glass facades, modern entrance systems, and dynamic interior glazing creating an energetic dining atmosphere. This 4,200 square foot restaurant combines functionality with striking visual appeal. The storefront features large-format glass panels with colored interlayers creating a distinctive brand identity. Automated sliding doors at the entrance include high-capacity operators for peak-hour traffic. Interior applications feature glass partitions creating flexible dining zones, glass drink display coolers with LED lighting, and decorative glass panels with the restaurant's logo. The project includes commercial kitchen glazing meeting health department requirements, grease-resistant coatings, and acoustic glass reducing noise transmission to adjacent spaces.",
    image: "/projects/Hot Millions/IMG-20231128-WA0004.jpg",
    gallery: [
      "/projects/Hot Millions/IMG-20231128-WA0004.jpg",
      "/projects/Hot Millions/IMG-20231128-WA0005.jpg",
      "/projects/Hot Millions/IMG-20231128-WA0006.jpg",
      "/projects/Hot Millions/IMG-20231128-WA0007.jpg",
    ],
    stats: {
      area: "4,200 sq ft",
      duration: "5 months",
    },
    featured: false,
    status: "Completed",
  },
  {
    id: 31,
    slug: "cafe-zirakpur",
    title: "Café Zirakpur",
    location: "Zirakpur, Punjab",
    year: "2023",
    category: "Hospitality",
    description: "A contemporary café featuring modern glass storefronts, automated entrance systems, and inviting interior glazing. This 2,800 square foot café creates a welcoming environment with extensive use of architectural glass. The facade features bi-fold glass doors allowing complete opening to outdoor seating during pleasant weather. Automated entrance doors include touchless sensors for high-traffic periods. Interior applications feature glass counters displaying baked goods, glass partitions creating cozy seating nooks, and large-format windows maximizing natural light. The project includes custom glass signage, LED-lit glass shelving for merchandise display, and easy-to-clean glass surfaces meeting food service requirements.",
    image: "/projects/Cafe, zirakpur/b15a690c-48d6-4edc-a75e-6e7ac93a6aef.JPG",
    gallery: [
      "/projects/Cafe, zirakpur/b15a690c-48d6-4edc-a75e-6e7ac93a6aef.JPG",
      "/projects/Cafe, zirakpur/ca493fa2-3bb9-4a10-83d3-2547beba81f0.JPG",
      "/projects/Cafe, zirakpur/e385a71f-376c-4eb5-a6fd-9118791fdc15.JPG",
      "/projects/Cafe, zirakpur/PHOTO-2020-06-03-16-55-14.jpg",
      "/projects/Cafe, zirakpur/PHOTO-2020-06-03-16-55-19.jpg",
      "/projects/Cafe, zirakpur/PHOTO-2020-06-03-16-55-20.jpg",
      "/projects/Cafe, zirakpur/PHOTO-2020-06-03-16-55-55.jpg",
      "/projects/Cafe, zirakpur/PHOTO-2020-06-03-16-55-56.jpg",
      "/projects/Cafe, zirakpur/PHOTO-2020-06-03-16-55-59.jpg",
      "/projects/Cafe, zirakpur/PHOTO-2020-06-03-16-56-00.jpg",
    ],
    stats: {
      area: "2,800 sq ft",
      duration: "4 months",
    },
    featured: false,
    status: "Completed",
  },
  {
    id: 32,
    slug: "jammu-banquet",
    title: "Jammu Banquet Hall",
    location: "Jammu, Jammu & Kashmir",
    year: "2024",
    category: "Hospitality",
    description: "A grand banquet facility featuring expansive glass facades, elegant entrance systems, and sophisticated interior glazing for events and celebrations. This 12,000 square foot venue combines architectural grandeur with functional flexibility. The installation features floor-to-ceiling curtain walls providing natural light and views of landscaped grounds. Automated entrance systems include wide-opening doors accommodating large guest numbers and equipment movement. The project includes operable glass partitions allowing space reconfiguration for events of various sizes, decorative laminated glass with custom patterns in foyer areas, and impact-resistant glazing in high-traffic zones. Specialty features include mood lighting integration, acoustic control for entertainment, and elegant glass balustrades at mezzanine levels.",
    image: "/projects/Jammu Banquet/1eb2979d-2575-42f2-98ed-7c3aac918985.JPG",
    gallery: [
      "/projects/Jammu Banquet/1eb2979d-2575-42f2-98ed-7c3aac918985.JPG",
      "/projects/Jammu Banquet/54b06ab9-dce8-46ad-a795-f324a47a9a3e.JPG",
      "/projects/Jammu Banquet/65f3af4d-6930-4efc-bf29-2158517fe702.JPG",
      "/projects/Jammu Banquet/79020a7e-b877-45fb-8efb-952b896d05c3.JPG",
      "/projects/Jammu Banquet/a1c6919d-dcee-4497-9561-d6fe1797a683.JPG",
      "/projects/Jammu Banquet/cb95e68a-32f7-4c22-b50d-457abdc86f66.JPG",
      "/projects/Jammu Banquet/cec37f31-b3ab-479a-955f-2604da183835.JPG",
      "/projects/Jammu Banquet/de730d85-5ec7-4c01-9fdf-5ab3945032c5.JPG",
      "/projects/Jammu Banquet/f7575d94-4b08-4e1b-9ff4-768d02e5bf79.JPG",
      "/projects/Jammu Banquet/WhatsApp Image 2022-03-14 at 10.27.18 AM.jpeg",
    ],
    stats: {
      area: "12,000 sq ft",
      duration: "8 months",
    },
    featured: false,
    status: "Completed",
  },
  {
    id: 33,
    slug: "hersoria-healthcare",
    title: "Hersoria Healthcare Center",
    location: "Haryana",
    year: "2023",
    category: "Healthcare",
    description: "A modern healthcare facility featuring hygienic glazing systems, secure entrance solutions, and patient-friendly facades. This 16,000 square foot medical center prioritizes cleanliness, natural light, and patient comfort. The installation features antimicrobial coated glass surfaces reducing pathogen transmission, hermetically sealed window systems preventing dust infiltration, and automated sliding doors with touchless sensors minimizing contact points. Interior applications include fire-rated glass assemblies protecting critical areas while maintaining visibility, acoustic glazing creating private consultation rooms, and impact-resistant glass in high-activity pediatric zones. The project includes specialized applications such as X-ray room lead glass, cleanroom glazing for surgical areas, and easy-to-sanitize surface treatments throughout.",
    image: "/projects/Hersoria Healthcare/20221117_124318.jpg",
    gallery: [
      "/projects/Hersoria Healthcare/20221117_124318.jpg",
      "/projects/Hersoria Healthcare/20221117_124329.jpg",
      "/projects/Hersoria Healthcare/20221117_124443.jpg",
      "/projects/Hersoria Healthcare/20221117_124557.jpg",
      "/projects/Hersoria Healthcare/20221117_124608.jpg",
      "/projects/Hersoria Healthcare/20221117_124616.jpg",
      "/projects/Hersoria Healthcare/20221117_124621.jpg",
      "/projects/Hersoria Healthcare/20221117_124622.jpg",
      "/projects/Hersoria Healthcare/20221117_124642.jpg",
      "/projects/Hersoria Healthcare/20221117_124705.jpg",
    ],
    stats: {
      area: "16,000 sq ft",
      duration: "11 months",
    },
    featured: false,
    status: "Completed",
  },
  {
    id: 34,
    slug: "resthouse",
    title: "Government Rest House",
    location: "Punjab",
    year: "2022",
    category: "Government",
    description: "A government guest accommodation facility featuring durable glazing systems, secure entrance solutions, and low-maintenance facades. This 10,000 square foot facility provides comfortable accommodation for government officials and guests. The installation features standard commercial window systems with enhanced security features, automated entrance doors with access control and visitor logging, and weather-resistant aluminum cladding requiring minimal upkeep. Room glazing incorporates acoustic performance for guest privacy and comfort. The project includes energy-efficient double glazing reducing operational costs, aluminum sun shades on south and west facades, and durable powder-coated finishes withstanding harsh weather. Safety features include tempered glass throughout and emergency egress compliant windows.",
    image: "/projects/Resthouse/086ffd2e-b73e-45b7-9dbf-9e02d5941e3d.JPG",
    gallery: [
      "/projects/Resthouse/086ffd2e-b73e-45b7-9dbf-9e02d5941e3d.JPG",
      "/projects/Resthouse/2020092811-1.jpg",
      "/projects/Resthouse/2020092828.png",
      "/projects/Resthouse/6f5e5cb4-fc84-4899-8f99-bbfb742580a0.JPG",
      "/projects/Resthouse/IMG-20190119-WA0003.jpg",
      "/projects/Resthouse/IMG-20190119-WA0008.jpg",
      "/projects/Resthouse/IMG-20190119-WA0009.jpg",
      "/projects/Resthouse/IMG-20190119-WA0010.jpg",
      "/projects/Resthouse/IMG-20190119-WA0011.jpg",
      "/projects/Resthouse/IMG-20190119-WA0012.jpg",
    ],
    stats: {
      area: "10,000 sq ft",
      duration: "7 months",
    },
    featured: false,
    status: "Completed",
  },
  {
    id: 35,
    slug: "labotek",
    title: "Labotek Industrial Facility",
    location: "Punjab",
    year: "2023",
    category: "Industrial",
    description: "An industrial manufacturing facility featuring durable glazing systems, industrial entrance solutions, and functional facades designed for production environments. This 22,000 square foot facility prioritizes durability, safety, and operational efficiency. The installation features impact-resistant polycarbonate glazing in production areas, industrial-grade automatic doors with heavy-duty operators and safety sensors, and aluminum composite panel cladding resistant to industrial pollutants. Office areas incorporate standard commercial systems with acoustic control. The project includes specialized applications such as viewing windows for quality control, fire-rated assemblies at production boundaries, and natural smoke ventilation systems. Sustainable features include translucent panels providing natural daylighting to production areas reducing energy costs.",
    image: "/projects/Labotek/IMG-20190111-WA0003.jpg",
    gallery: [
      "/projects/Labotek/IMG-20190111-WA0003.jpg",
      "/projects/Labotek/IMG-20190111-WA0004.jpg",
      "/projects/Labotek/IMG-20190111-WA0006.jpg",
      "/projects/Labotek/IMG-20190111-WA0007.jpg",
      "/projects/Labotek/IMG-20190111-WA0008.jpg",
      "/projects/Labotek/IMG-20190111-WA0011.jpg",
      "/projects/Labotek/IMG-20190111-WA0012.jpg",
      "/projects/Labotek/IMG-20190111-WA0014.jpg",
      "/projects/Labotek/IMG-20190111-WA0015.jpg",
    ],
    stats: {
      area: "22,000 sq ft",
      duration: "9 months",
    },
    featured: false,
    status: "Completed",
  },
  {
    id: 36,
    slug: "kangaroo",
    title: "Kangaroo Kids School",
    location: "Punjab",
    year: "2024",
    category: "Education",
    description: "A vibrant preschool and daycare facility featuring child-safe glazing systems, secure entrance solutions, and colorful architectural elements. This 8,500 square foot educational facility creates a safe, stimulating environment for young learners. The installation features laminated safety glass throughout preventing sharp edges if broken, child-height windows encouraging outdoor observation and learning, and automated entrance doors with child-safety sensors. Interior applications include colorful decorative laminated glass with playful patterns, rounded glass corners eliminating sharp edges, and easy-to-clean surfaces. Security features include access control systems preventing unauthorized entry, impact-resistant glazing in active play areas, and unbreakable polycarbonate in potentially high-impact locations. The project incorporates natural daylighting strategies supporting childhood development.",
    image: "/projects/Kangaroo/Picture1.jpg",
    gallery: [
      "/projects/Kangaroo/Picture1.jpg",
      "/projects/Kangaroo/Picture10.jpg",
      "/projects/Kangaroo/Picture11.jpg",
      "/projects/Kangaroo/Picture12.jpg",
      "/projects/Kangaroo/Picture13.jpg",
      "/projects/Kangaroo/Picture2.jpg",
      "/projects/Kangaroo/Picture3.jpg",
      "/projects/Kangaroo/Picture4.jpg",
      "/projects/Kangaroo/Picture5.jpg",
      "/projects/Kangaroo/Picture6.jpg",
    ],
    stats: {
      area: "8,500 sq ft",
      duration: "6 months",
    },
    featured: false,
    status: "Completed",
  },
  {
    id: 37,
    slug: "strawberry",
    title: "Strawberry Retail Store",
    location: "Punjab",
    year: "2023",
    category: "Retail",
    description: "A fashion retail store featuring modern glass storefronts, automated entrance systems, and attractive display glazing. This 3,200 square foot retail space maximizes visibility and customer appeal. The storefront features large-format clear glass creating unobstructed views of merchandise displays. Automated sliding entrance doors include anti-theft sensors and integration with store security systems. Interior applications include glass fitting room enclosures, mirrored display walls, and glass shelving systems. The project features specialty applications such as LED-lit glass signage, custom-etched glass with brand elements, and sophisticated ambient lighting highlighting merchandise. Anti-glare coatings ensure optimal product visibility while reducing screen glare for digital displays.",
    image: "/projects/Strawberry/WhatsApp Image 2025-02-04 at 17.30.12_d82e7f2e.jpg",
    gallery: [
      "/projects/Strawberry/WhatsApp Image 2025-02-04 at 17.30.12_d82e7f2e.jpg",
    ],
    stats: {
      area: "3,200 sq ft",
      duration: "4 months",
    },
    featured: false,
    status: "Completed",
  },
  {
    id: 38,
    slug: "chandelier",
    title: "Chandelier Showroom",
    location: "Punjab",
    year: "2023",
    category: "Retail",
    description: "An elegant lighting showroom featuring expansive glass facades, sophisticated entrance systems, and dramatic interior glazing showcasing premium light fixtures. This 4,800 square foot showroom creates an immersive lighting experience. The storefront features extra-clear low-iron glass providing true color rendition for displayed fixtures. Automated entrance systems include elegant revolving doors creating a premium entry experience. Interior applications feature high ceilings with structural glazing maximizing natural light, glass display cases with integrated LED lighting, and frameless glass partitions creating flexible display zones. The project incorporates sophisticated lighting control systems, mirror and glass combinations amplifying light effects, and black-framed glass accents creating dramatic visual contrast.",
    image: "/projects/Chandelier/08dbefe2-880e-44b8-998f-b8f6f4084a02.JPG",
    gallery: [
      "/projects/Chandelier/08dbefe2-880e-44b8-998f-b8f6f4084a02.JPG",
      "/projects/Chandelier/0a6da66b-cbb7-4dc2-a8f8-caf585372a07.JPG",
      "/projects/Chandelier/0b5aedfd-5af1-49b4-8c68-9b058c2c09d2.JPG",
      "/projects/Chandelier/38718206-81ba-4a29-9362-f65700e7fd50.JPG",
      "/projects/Chandelier/5820bc49-2baa-428f-8e54-c0c8fa845d21.JPG",
      "/projects/Chandelier/68b811c7-dc67-49da-b88b-f4c02ac253ef.JPG",
      "/projects/Chandelier/6d415543-2e00-4579-9237-419afea50ecf (2).JPG",
      "/projects/Chandelier/72233dfa-ba42-4ed4-b9ae-795fe92116f7.JPG",
      "/projects/Chandelier/991749e0-c05b-4388-a202-5e0a8980cae9.JPG",
      "/projects/Chandelier/a8ed5db1-0646-4c6e-82c9-290883d8ac4f.JPG",
    ],
    videoUrl: "/projects/Chandelier/VIDEO-2020-02-03-12-08-15.mp4",
    stats: {
      area: "4,800 sq ft",
      duration: "5 months",
    },
    featured: false,
    status: "Completed",
  },
  {
    id: 39,
    slug: "cp-67",
    title: "CP-67 Commercial Plaza",
    location: "Chandigarh",
    year: "2024",
    category: "Commercial",
    description: "A mixed-use commercial development in Chandigarh's Central Business District featuring contemporary glass facades, modern entrance systems, and premium architectural finishes. This 42,000 square foot project establishes a new architectural standard for the area. The curtain wall system features high-performance glass with selective coatings optimizing natural light while reducing solar heat gain by 60%. Automated entrance systems include elegant revolving doors at main lobbies and high-speed sliding doors at retail entrances. The installation incorporates unitized curtain wall panels for rapid installation and weather-tight performance, aluminum composite panel accents in complementary finishes, and structural glass canopies at building entrances. Interior applications include full-height glass in elevator lobbies, frameless glass railings at atrium spaces, and sophisticated way-finding signage systems.",
    image: "/projects/CP 67/PHOTO-2022-09-09-13-16-16.jpg",
    gallery: [
      "/projects/CP 67/PHOTO-2022-09-09-13-16-16.jpg",
      "/projects/CP 67/PHOTO-2022-09-09-13-16-17.jpg",
      "/projects/CP 67/PHOTO-2022-09-09-13-16-18.jpg",
    ],
    stats: {
      area: "42,000 sq ft",
      duration: "15 months",
    },
    featured: false,
    status: "Completed",
  },
  {
    id: 40,
    slug: "hansi",
    title: "Hansi Commercial Complex",
    location: "Hansi, Haryana",
    year: "2023",
    category: "Commercial",
    description: "A modern commercial complex featuring contemporary glazing systems, automated entrance solutions, and durable facades designed for small-town commercial development. This 18,000 square foot project brings metropolitan design standards to a tier-2 city. The installation features commercial storefront systems with large display windows, automated sliding entrance doors with reliable operators suited for frequent use, and aluminum composite panel cladding in modern finishes. Office spaces incorporate standard commercial windows with energy-efficient glazing. The project includes glass canopies at building entrances providing weather protection, stainless steel and glass railings at upper floors, and illuminated signage systems for tenant identification. Cost-effective solutions ensure long-term durability with minimal maintenance requirements.",
    image: "/projects/Hansi/IMG-20250421-WA0018.jpg",
    gallery: [
      "/projects/Hansi/IMG-20250421-WA0018.jpg",
      "/projects/Hansi/IMG-20250421-WA0019.jpg",
      "/projects/Hansi/IMG-20250421-WA0020.jpg",
      "/projects/Hansi/IMG-20250421-WA0021.jpg",
      "/projects/Hansi/IMG-20250421-WA0022.jpg",
      "/projects/Hansi/IMG-20250421-WA0023.jpg",
      "/projects/Hansi/IMG-20250421-WA0024.jpg",
      "/projects/Hansi/IMG-20250421-WA0025.jpg",
      "/projects/Hansi/IMG-20250421-WA0026.jpg",
      "/projects/Hansi/IMG-20250421-WA0027.jpg",
    ],
    videoUrl: "/projects/Hansi/VID-20250421-WA0001.mp4",
    stats: {
      area: "18,000 sq ft",
      duration: "8 months",
    },
    featured: false,
    status: "Completed",
  },
  {
    id: 41,
    slug: "bhoj-nagar-sample",
    title: "Bhoj Nagar Sample Home",
    location: "Haryana",
    year: "2024",
    category: "Residential",
    description: "A model home showcasing premium residential glazing solutions, modern entrance systems, and contemporary architectural finishes for a residential development. This 4,500 square foot sample home demonstrates the quality standards for the entire development. The installation features energy-efficient uPVC window systems with multi-chambered profiles and multi-point locking, automated entrance systems with smart home integration and remote access, and expansive sliding glass doors creating indoor-outdoor living spaces. Interior applications include glass stair railings with stainless steel posts, modern shower enclosures with minimal framing, and glass partition options for flexible room layouts. The project showcases various finish options including powder-coated aluminum in multiple colors, decorative laminated glass patterns, and integrated blind systems.",
    image: "/projects/Bhoj Nagar Sample/IMG-20250729-WA0027.jpg",
    gallery: [
      "/projects/Bhoj Nagar Sample/IMG-20250729-WA0027.jpg",
      "/projects/Bhoj Nagar Sample/IMG-20250729-WA0028.jpg",
      "/projects/Bhoj Nagar Sample/IMG-20250729-WA0030.jpg",
      "/projects/Bhoj Nagar Sample/IMG-20250729-WA0039.jpg",
      "/projects/Bhoj Nagar Sample/IMG-20250729-WA0040.jpg",
      "/projects/Bhoj Nagar Sample/IMG-20250729-WA0041.jpg",
      "/projects/Bhoj Nagar Sample/IMG-20250729-WA0042.jpg",
    ],
    stats: {
      area: "4,500 sq ft",
      duration: "5 months",
    },
    featured: false,
    status: "Completed",
  },
  {
    id: 42,
    slug: "jubilee-pics",
    title: "Jubilee Multiplex Cinema",
    location: "Chandigarh",
    year: "2022",
    category: "Entertainment",
    description: "A modern multiplex cinema featuring dramatic glass facades, sophisticated entrance systems, and specialized glazing for entertainment venues. This 35,000 square foot entertainment complex creates an immersive movie-going experience. The installation features floor-to-ceiling curtain walls at the main facade creating an impressive street presence with LED-integrated glazing for dynamic visual displays. Automated entrance systems include wide-opening doors for crowd management and integration with ticketing systems. Interior applications include acoustic glazing isolating cinema halls from common areas, fire-rated glass assemblies protecting exit corridors while maintaining visibility, and decorative laminated glass in F&B areas. The project incorporates specialized applications such as projection room glazing with light-control properties and VIP lounge partitions with privacy glass technology.",
    image: "/projects/Jubilee pics/24a5df0c-e738-4804-8958-74398f2fabae.JPG",
    gallery: [
      "/projects/Jubilee pics/24a5df0c-e738-4804-8958-74398f2fabae.JPG",
      "/projects/Jubilee pics/3.jpg",
      "/projects/Jubilee pics/3a43ffcd-a73e-42a1-adea-ad165d826abf.JPG",
      "/projects/Jubilee pics/42645e0d-795d-45bd-87c9-03e31bf38918.JPG",
      "/projects/Jubilee pics/5e1b638e-7a97-480e-92f0-08eb7bd5b7d2.JPG",
      "/projects/Jubilee pics/6293b507-6b51-425a-a680-eba52ec0fc7f.JPG",
      "/projects/Jubilee pics/889d555d-ad13-4e0a-b0bb-a26481f9410c.JPG",
      "/projects/Jubilee pics/9.jpg",
      "/projects/Jubilee pics/a51fb0b0-82e1-45d4-b20a-3b5d10e9e4fb.JPG",
      "/projects/Jubilee pics/a835c1c8-b0c8-4daa-88c1-176caf77c8e0.JPG",
    ],
    stats: {
      area: "35,000 sq ft",
      duration: "13 months",
    },
    featured: false,
    status: "Completed",
  },
  {
    id: 43,
    slug: "dorma-images",
    title: "DORMA Product Installation Gallery",
    location: "Multiple Locations",
    year: "2023",
    category: "Commercial",
    description: "A showcase of DORMA automatic door systems and architectural hardware installations across various project types. This portfolio represents our partnership with DORMA (now dormakaba) implementing their premium automatic door solutions across commercial, institutional, and hospitality projects. The installations feature heavy-duty automatic sliding door operators with advanced sensor technology, elegant revolving door systems providing energy-efficient building entrances, and sophisticated access control integration. Projects include high-traffic retail locations requiring reliability for millions of annual cycles, healthcare facilities with touchless operation reducing infection risk, and corporate offices with sophisticated access management. The portfolio demonstrates expertise in specification, installation, commissioning, and maintenance of automatic entrance systems meeting international standards for safety, durability, and performance.",
    image: "/projects/DORMA Images/DDC Chd/07012010684.jpg",
    gallery: [
      "/projects/DORMA Images/DDC Chd/07012010684.jpg",
      "/projects/DORMA Images/DDC Chd/07012010685.jpg",
      "/projects/DORMA Images/DDC Chd/07012010686.jpg",
      "/projects/DORMA Images/DDC Chd/07012010687.jpg",
      "/projects/DORMA Images/DDC Chd/07012010688.jpg",
      "/projects/DORMA Images/HPCA/09082009464.jpg",
      "/projects/DORMA Images/HPCA/09082009465.jpg",
      "/projects/DORMA Images/HPCA/09082009466.jpg",
      "/projects/DORMA Images/HPCA/09082009467.jpg",
      "/projects/DORMA Images/HPCA/09082009468.jpg",
    ],
    stats: {
      area: "Varies by project",
      duration: "Ongoing partnership",
    },
    featured: false,
    status: "Completed",
  },
]

// Helper functions for filtering and finding projects
export const getFeaturedProjects = () => allProjects.filter((p) => p.featured)

export const getProjectBySlug = (slug: string) => allProjects.find((p) => p.slug === slug)

export const getProjectsByCategory = (category: string) =>
  category === "All" ? allProjects : allProjects.filter((p) => p.category === category)

export const getAllCategories = () => {
  const categories = Array.from(new Set(allProjects.map((p) => p.category)))
  return ["All", ...categories.sort()]
}
